name: annotations_example
description: Demonstrates how to use the annotations package.
publish_to: 'none'

environment:
  sdk: ^3.10.8

dependencies:
  annotations:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
