name: dart_annotations
description: A Dart analyzer plugin providing the annotations and static analysis rules for them.
version: 1.0.3
repository: https://github.com/yaroslav13/annotations

environment:
  sdk: ^3.9.0

dependencies:
  analysis_server_plugin: ^0.3.8
  analyzer: ^10.0.2
  meta: ^1.18.1

dev_dependencies:
  test: ^1.29.0


