name: dart_annotations
description: A Dart analyzer plugin providing the annotations and static analysis rules for them.
version: 1.0.0
repository: https://github.com/yaroslav13/annotations

environment:
  sdk: ^3.10.8

dependencies:
  analysis_server_plugin: ^0.3.0
  analyzer_plugin: ^0.13.0
  analyzer: ^8.0.0

dev_dependencies:
  test: ^1.25.0


